AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Appointment Booking & Availability Management System (SAM)

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        TABLE_NAME: appointment-system-dev
    

Resources:

  ############################
  # API Gateway
  ############################
  AppointmentApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,PUT'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"

  ############################
  # Lambda Functions (API)
  ############################

  CreateProviderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      CodeUri: .build
      Handler: src/handlers/providers/create-provider.handler
      Environment:
        Variables:
          TABLE_NAME: appointment-system-dev
      Policies:
        - DynamoDBCrudPolicy:
            TableName: appointment-system-dev
      Events:
        CreateProviderApi:
          Type: Api
          Properties:
            Path: /providers
            Method: post
            RestApiId: !Ref AppointmentApi
            


  CreateAvailabilityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build
      Handler: src/handlers/availability/create-availability.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: appointment-system-dev
      Events:
        CreateAvailabilityApi:
          Type: Api
          Properties:
            Path: /providers/{providerId}/availability
            Method: post
            RestApiId: !Ref AppointmentApi


  GetSlotsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build
      Handler: src/handlers/slot/get-slot.handler
      Events:
        GetSlotsApi:
          Type: Api
          Properties:
            Path: /providers/{providerId}/slots
            Method: get
            RestApiId: !Ref AppointmentApi

  CreateBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build
      Handler: src/handlers/booking/create-booking.handler
      Environment:
        Variables:
          BOOKING_QUEUE_URL: !Ref BookingQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: appointment-system-dev-booking-queue
        - DynamoDBCrudPolicy:
            TableName: appointment-system-dev
      Events:
        CreateBookingApi:
          Type: Api
          Properties:
            Path: /bookings
            Method: post
            RestApiId: !Ref AppointmentApi

  ConfirmBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build
      Handler: src/handlers/booking/confirm-booking.handler
      Policies:
        - SQSSendMessagePolicy:
            QueueName: appointment-system-dev-booking-queue
        - DynamoDBCrudPolicy:
            TableName: appointment-system-dev
      Events:
        ConfirmBookingApi:
          Type: Api
          Properties:
            Path: /bookings/{bookingId}/confirm
            Method: post
            RestApiId: !Ref AppointmentApi

  CancelBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build
      Handler: src/handlers/booking/cancel-booking.handler
      Policies:
        - SQSSendMessagePolicy:
            QueueName: appointment-system-dev-booking-queue
        - DynamoDBCrudPolicy:
            TableName: appointment-system-dev
      Events:
        CancelBookingApi:
          Type: Api
          Properties:
            Path: /bookings/{bookingId}/cancel
            Method: post
            RestApiId: !Ref AppointmentApi

  GetBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build
      Handler: src/handlers/booking/get-booking.handler
      Events:
        GetBookingApi:
          Type: Api
          Properties:
            Path: /bookings/{bookingId}
            Method: get
            RestApiId: !Ref AppointmentApi

  ############################
  # Lambda Workers
  ############################

  BookingWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build
      Handler: src/workers/booking-processor.handler
      Policies:
        - SQSSendMessagePolicy:
            QueueName: appointment-system-dev-booking-queue
        - DynamoDBCrudPolicy:
            TableName: appointment-system-dev
      Events:
        BookingQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt BookingQueue.Arn
            BatchSize: 10

  ExpirationWorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .build
      Handler: src/workers/expiration-processor.handler
      Timeout: 30
      Policies:
        - DynamoDBCrudPolicy:
            TableName: appointment-system-dev
      Events:
        ExpirationSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Name: booking-expiration-scheduler
            Description: "Expire stale PENDING bookings and release slots"
            Enabled: true

      # Schedule intentionally disabled (same as your YAML)

  ############################
  # DynamoDB
  ############################

  AppointmentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: appointment-system-dev
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
        - AttributeName: GSI3PK
          AttributeType: S
        - AttributeName: GSI3SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI3
          KeySchema:
            - AttributeName: GSI3PK
              KeyType: HASH
            - AttributeName: GSI3SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  ############################
  # SQS + DLQ
  ############################

  BookingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: appointment-system-dev-booking-dlq
      MessageRetentionPeriod: 1209600

  BookingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: appointment-system-dev-booking-queue
      VisibilityTimeout: 300
      MessageRetentionPeriod: 1209600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt BookingDLQ.Arn
        maxReceiveCount: 3

Outputs:
  ApiUrl:
    Description: API Gateway endpoint
    Value: !Sub "https://${AppointmentApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"

  AppointmentTableName:
    Value: !Ref AppointmentTable

  BookingQueueUrl:
    Value: !Ref BookingQueue

  BookingDLQUrl:
    Value: !Ref BookingDLQ
